### ISSUE TITLE
Is 700 mhz better or 2.4?

### ISSUE THREAD

**Issue by radding** [MythicApps/badges#1]
We need to figure this out.

**Comment by jason-merlo** [comment]
I think we want to use ZigBee, I know for sure it can operate at 2.4GHz, not sure if it has spec to operate on the 700MHz range or not.  The 700MHz would allow for longer range comms with less power consumption which is definitely a plus, and it avoids the further degradation of the 2.4GHz spectrum that the majority of devices will already be on.

So it sounds like, if at all possible, we should stray from 2.4GHz, whether that be 700MHz or not, I can't say at this point.

**Comment by radding** [comment]
But you get more data over 2.4 ghz. We need to see how much data we will use

**Comment by Badsauce** [comment]
I imagine the data usage will be pretty low, we're not streaming video or passing gifs around. We're most likely sending small push notification strings and meal pass booleans

**Comment by radding** [comment]
Then 700MHz sounds like the better option

**Comment by jason-merlo** [comment]
I highly doubt we'll need comms greater than 115200 baud, personally.  We're just streaming small messages to badges and receiving back simple messages with personal identifiers.  

If half the attendees sent a 30 character message at the same time we would just hit our max capacity.  We could probably go all the way up to 250k on 700MHz without issue.
